### PR TITLE
Remove python 2 support and assume we have python 3.3+

### PR DESCRIPTION
**Pull request by behrmann**
I had this lying around on some private branch, seeing the movement here, I remembered that I might push it. Python 2 has been EOL for 2 years now and everything older 3.7 is EOL as well, so assuming Python 3.3+ seems sensible (also nothing older thatn 3.7 is being tested).

### CODE REVIEW

**Comment by keszybz** [comment]
Yeah, but let's do this for the next release.

**Comment by behrmann** [comment]
Sure, no worries. This is not really pressing. I still had this lying around from when I was last looking at the code and wanted to make it a bit easier to read.

What I wondered: Is there a deeper reason behind this being extension modules instead of e.g. `ctypes`?

**Comment by thatguystone** [comment]
Is there any reason to restrict to 3.3+? I have type-hints locally that would be nice to get merged, but that requires 3.5+.

**Comment by thatguystone** [comment]
Is there any reason to restrict to 3.3+? I have type-hints locally that would be nice to get merged, but that requires 3.5+.

**Comment by behrmann** [comment]
Well, it does make the code easier to follow and everything pre-3.7 is EOL upstream. The system's running EOL Python versions probably don't need the newest version of this module and will be served by an older version.

**Pull request merged**
